--- !ditz.rubyforge.org,2008-03-06/project 
name: libkoki
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: libkoki
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.0"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2011-08-11 20:59:37.742926 Z
    - Chris Kirkham <chrisjameskirkham@gmail.com>
    - created
    - A feature complete library ready for public use
